import { createElement } from '@lwc/engine-dom';
import LCC_CustomCSVExport from 'c/lCC_CustomCSVExport';

describe('c-l-c-c-custom-csv-export', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-c-c-custom-csv-export', {
            is: LCC_CustomCSVExport
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});